name: kkiri
description: "A Flutter app connecting exchange students in Korea."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  go_router: ^14.1.4
  shared_preferences: ^2.2.3
  http: ^1.2.1
  intl: ^0.20.0

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  google_sign_in: ^6.2.1

  # Map/Location
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  geoflutterfire_plus: ^0.0.32

  # Image
  image_picker: ^1.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
