name: kkiri
description: "A Flutter app connecting exchange students in Korea."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  google_sign_in: ^6.2.1
  firebase_storage: ^12.3.1
  google_maps_flutter: ^2.7.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  geoflutterfire_plus: ^0.0.27
  http: ^1.2.0
  image_picker: ^1.0.7
  go_router: ^14.2.2
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
